# Generated by Django 5.2 on 2025-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pagamento Pendente'), ('E', 'Em separação'), ('T', 'Em transporte'), ('C', 'Concluído'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
